# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])
print(a1.shape, a1.ndim)

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],
              [4,5,6]])
print(a2.shape, a2.ndim)
# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],
               [4,5,6]],
              [[7,8,9],
              [10,11,12]],
              [[13,14,15],
              [16,17,18]]])
print(a3.shape, a3.ndim)

(3,) 1
(2, 3) 2
(3, 2, 3) 3


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [52]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((3, 2, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [55]:
# Import pandas and create a DataFrame out of one
import pandas as pd
# of the arrays you've created
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [56]:
# Create an array of shape (10, 2) with only ones
ones_array = np.ones(20).reshape(10,2)
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [57]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_array = np.zeros(42).reshape(7,2,3)
zeros_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [58]:
# Create an array within a range of 0 and 100 with step 3
array_range = np.array(range(0,100,3))
array_range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [60]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(1,10,size=(7,2))
random_array

array([[7, 1],
       [1, 5],
       [8, 6],
       [1, 2],
       [6, 1],
       [2, 9],
       [4, 2]])

In [62]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_float = np.random.random((3,5))
random_array_float

array([[0.99496389, 0.96657847, 0.66060178, 0.83439902, 0.45516062],
       [0.83978582, 0.56118822, 0.14444887, 0.52975876, 0.39452675],
       [0.213333  , 0.94539621, 0.35346105, 0.70844654, 0.64558718]])

In [64]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_seed = np.random.randint(1,10,size=(4,6))
random_array_seed

array([[7, 4, 8, 5, 7, 3],
       [7, 8, 5, 4, 8, 8],
       [3, 6, 5, 2, 8, 6],
       [2, 5, 1, 6, 9, 1]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [66]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_numbers = np.random.randint(1,10,size=(3,7))
random_numbers

# Find the unique numbers in the array you just created
np.unique(random_numbers)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
# Find the 0'th index of the latest array you created
random_numbers[0]

array([3, 1, 4, 2, 8, 4, 2])

In [68]:
# Get the first 2 rows of latest array you created
random_numbers[:2]

array([[3, 1, 4, 2, 8, 4, 2],
       [6, 6, 4, 6, 2, 2, 4]])

In [69]:
# Get the first 2 values of the first 2 rows of the latest array
random_numbers[:2,:2]

array([[3, 1],
       [6, 6]])

In [70]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_numbers_2 = np.random.randint(0,10,size=(3,5))
ones_array_2 = np.ones((3,5))

In [71]:
# Add the two arrays together
random_numbers_2 + ones_array_2

array([[ 8., 10.,  9.,  9.,  1.],
       [ 9.,  7.,  9.,  8.,  1.],
       [ 8.,  8.,  3.,  1.,  8.]])

In [72]:
# Create another array of ones of shape (5, 3)
ones_array_3 = np.ones((5,3))
ones_array_3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [73]:
# Try add the array of ones and the other most recent array together
ones_array_3 + ones_array_2

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [74]:
# Create another array of ones of shape (3, 5)
ones_array_4 = np.ones((3,5))
ones_array_4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [81]:
# Subtract the new array of ones from the other most recent array
ones_array_4 - random_numbers_2

array([[-6., -8., -7., -7.,  1.],
       [-7., -5., -7., -6.,  1.],
       [-6., -6., -1.,  1., -6.]])

In [80]:
# Multiply the ones array with the latest array
ones_array_4 * random_numbers_2

array([[7., 9., 8., 8., 0.],
       [8., 6., 8., 7., 0.],
       [7., 7., 2., 0., 7.]])

In [82]:
# Take the latest array to the power of 2 using '**'
random_numbers_2 ** 2

array([[49, 81, 64, 64,  0],
       [64, 36, 64, 49,  0],
       [49, 49,  4,  0, 49]])

In [83]:
# Do the same thing with np.square()
np.square(random_numbers_2)

array([[49, 81, 64, 64,  0],
       [64, 36, 64, 49,  0],
       [49, 49,  4,  0, 49]])

In [84]:
# Find the mean of the latest array using np.mean()
np.mean(random_numbers_2)

5.6

In [85]:
# Find the maximum of the latest array using np.max()
np.max(random_numbers_2)

9

In [86]:
# Find the minimum of the latest array using np.min()
np.min(random_numbers_2)

0

In [87]:
# Find the standard deviation of the latest array
np.std(random_numbers_2)

3.179098404684364

In [88]:
# Find the variance of the latest array
np.var(random_numbers_2)

10.106666666666667

In [96]:
# Reshape the latest array to (3, 5, 1)
random_numbers_2.reshape(3,5,1).T

array([[[7, 8, 7],
        [9, 6, 7],
        [8, 8, 2],
        [8, 7, 0],
        [0, 0, 7]]])

In [98]:
# Transpose the latest array
# random_numbers_2
random_numbers_2.T

array([[7, 8, 7],
       [9, 6, 7],
       [8, 8, 2],
       [8, 7, 0],
       [0, 0, 7]])

What does the transpose do?

In [99]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array_1 = np.random.randint(0,10,size=(3,3))
array_2 = np.random.randint(0,10,size=(3,2))

In [100]:
# Perform a dot product on the two newest arrays you created
np.dot(array_1, array_2)

array([[ 18,  14],
       [ 77,  64],
       [116,  99]])

In [101]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array_3 = np.random.randint(0,10, size=(4,3))
array_4 = np.random.randint(0,10, size=(4,3))

In [102]:
# Perform a dot product on the two newest arrays you created
np.dot(array_3,array_4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [103]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(array_3,array_4.T)

array([[ 99, 110,  38,  41],
       [105, 119,  44,  44],
       [ 36,  54,  12,  22],
       [ 42,  52,   4,  22]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [104]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array_5 = np.random.randint(0,10,size=(4,2))
array_6 = np.random.randint(0,10,size=(4,2))

In [105]:
# Compare the two arrays with '>'
array_5 > array_6

array([[False,  True],
       [False,  True],
       [False, False],
       [False,  True]])

What happens when you compare the arrays with `>`?

In [106]:
# Compare the two arrays with '>='
array_5 >= array_6

array([[False,  True],
       [False,  True],
       [False, False],
       [False,  True]])

In [107]:
# Find which elements of the first array are greater than 7
array_5 > 7

array([[False, False],
       [False, False],
       [False, False],
       [False,  True]])

In [108]:
# Which parts of each array are equal? (try using '==')
array_5 == array_6

array([[False, False],
       [False, False],
       [False, False],
       [False, False]])

In [109]:
# Sort one of the arrays you just created in ascending order
np.sort(array_5)

array([[6, 6],
       [3, 6],
       [2, 5],
       [1, 9]])

In [122]:
# Sort the indexes of one of the arrays you just created
np.argsort(array_5)

array([[0, 1],
       [0, 1],
       [0, 1],
       [0, 1]], dtype=int64)

In [112]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(array_5)

7

In [113]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(array_5)

6

In [115]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(array_5, axis=1)

array([0, 1, 1, 1], dtype=int64)

In [116]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(array_5, axis=0)

array([3, 2], dtype=int64)

In [120]:
# Create an array of normally distributed random numbers
random_distributed_array = np.random.random(1000)
random_distributed_array

array([0.35486083, 0.42477153, 0.21534438, 0.59709577, 0.59480321,
       0.37220039, 0.33303487, 0.88496431, 0.38328424, 0.49350099,
       0.28330476, 0.7867695 , 0.39744816, 0.51361105, 0.25335717,
       0.98765959, 0.29149574, 0.77074253, 0.42749565, 0.20621741,
       0.79971876, 0.33360679, 0.86519335, 0.91525718, 0.85982384,
       0.03500791, 0.78737335, 0.41133947, 0.87372292, 0.63795426,
       0.83364313, 0.49943177, 0.5350255 , 0.14438763, 0.78398736,
       0.41938961, 0.50008012, 0.78509771, 0.5988454 , 0.20109873,
       0.59023266, 0.40763286, 0.46952554, 0.02831127, 0.21002935,
       0.28103808, 0.71296001, 0.01149247, 0.40877726, 0.92402687,
       0.11188062, 0.51642439, 0.78652238, 0.94253131, 0.74677664,
       0.72056555, 0.82648809, 0.44620122, 0.80584453, 0.0079644 ,
       0.92456106, 0.44330651, 0.55338019, 0.25488225, 0.74253083,
       0.07663581, 0.8726358 , 0.82811683, 0.21606012, 0.8093244 ,
       0.78635773, 0.6322166 , 0.37352018, 0.27149875, 0.23178

In [121]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.array(range(1,100,10))

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.